#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           leftMotor,     tmotorVex269_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armtwoMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightclawMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftclawMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 1 Remote -                            *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*  The Group 6 buttons on the top-right of the VEXnet Joystick are used to raise and lower an arm.   *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
  while(1 == 1)
  {
    //Driving Motor Control
    motor[leftMotor] = vexRT[Ch2] / 2;
    motor[rightMotor] = vexRT[Ch3] / 2;

    //Arm Control
    if(vexRT[Btn6D] == 1)
    {
      motor[armMotor] = 20;
    }
    else if(vexRT[Btn6U] == 1)
    {
      motor[armMotor] = -40;
    }
    else
    {
      motor[armMotor] = -10;
    }

    //Arm Two Control
    if(vexRT[Btn5U] == 1)
    {
      motor[armtwoMotor] = 30;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[armtwoMotor] = -30;
    }
    else
    {
      motor[armtwoMotor] = 0;
    }

    //Claw Control
    if(vexRT[Btn8D] == 1)
    {
      motor[clawMotor] = 40;
    }
    else if(vexRT[Btn8U] == 1)
    {
      motor[clawMotor] = -40;
    }
    else
    {
      motor[clawMotor] = 10;
    }

    //Pincer Control
    if(vexRT[Btn7D] == 1)
    {
      motor[rightclawMotor] = 20;
    }
    else if(vexRT[Btn7U] == 1)
    {
      motor[rightclawMotor] = -20;
    }
    else
    {
      motor[rightclawMotor] = 0;
    }
    if(vexRT[Btn7U] == 1)
    {
      motor[leftclawMotor] = 20;
    }
    else if(vexRT[Btn7D] == 1)
    {
      motor[leftclawMotor] = -20;
    }
    else
    {
      motor[leftclawMotor] = 0;
    }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
